version: '3.8'

services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'backend-python-flask'
    command: 'gunicorn -w 5 -b 0.0.0.0:5000 "server:create_app()"'
    ports:
      - 5000:5000
    volumes: 
      - .:/app
